Repository wecode-bootcamp-korea/16-2nd-bestgo-backend, pull requests merged in 2021-01, with the labels that each got.

#1 [16기 장준영] Add: models.py 세팅
  bestgo/settings.py
  services/__init__.py
  services/admin.py
  services/apps.py
  services/migrations/0001_initial.py
  services/migrations/0002_auto_20210126_1237.py
  services/migrations/0003_auto_20210127_0211.py
  services/migrations/__init__.py
  services/models.py
  services/tests.py
  services/urls.py
  services/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/0002_auto_20210127_0211.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: Accepted

#4 [16기 장준영]Add: users, services models.py 추가
  services/migrations/0004_service_image_url.py
  services/models.py
  users/migrations/0003_auto_20210128_0453.py
  users/models.py
Labels: Status: 도움 요청, Status: 리뷰 요청

#5 [16기 정지원] Add: categories image_url field 추가
  services/migrations/0005_category_icon_image_url.py
  services/models.py
  users/migrations/0004_auto_20210128_0814.py
Labels: Status: 도움 요청, Status: 리뷰 요청

#2 [16기 장준영]Add: users app views.py 작성
  bestgo/urls.py
  services/urls.py
  users/tests.py
  users/urls.py
  users/utils.py
  users/views.py
Labels: Status: 리뷰 요청

#3 [16기 정지원] Add: CategoryView, ServiceListView(pr 내용 수정완료)
  bestgo/settings.py
  bestgo/urls.py
  requirements.txt
  services/migrations/0004_service_image_url.py
  services/tests.py
  services/urls.py
  services/views.py
  users/migrations/0004_auto_20210128_1537.py
  users/migrations/0005_merge_20210128_1745.py
Labels: Status: 리뷰 진행중

#6 [16기 정지원] Patch: services.models 데이터베이스 아키텍처 수정
  services/migrations/0006_auto_20210129_2318.py
  services/models.py
Labels: Status: 리뷰 요청
