Repository wecode-bootcamp-korea/16-2nd-bestgo-backend, pull requests merged in 2021-02, with the labels that each got.

#7 [16기 장준영]Add: users app views.py 작성& 피드백 반영
  services/urls.py
  users/tests.py
  users/urls.py
  users/utils.py
  users/views.py
Labels: Status: 리뷰 요청

#8 [16기 정지원] Add : (Question, Region,ServiceDetail)Views작성/unittest 완료
  .gitignore
  bestgo/settings.py
  db_uploader/db_uploader_region.py
  db_uploader_questions.py
  db_uploader_region.py
  services/tests.py
  services/urls.py
  services/views.py
  users/management/__init__.py
  users/management/commands/seed_users.py
  users/migrations/0006_auto_20210131_0237.py
  users/migrations/0007_auto_20210131_0317.py
  users/migrations/0008_auto_20210131_0317.py
  users/migrations/0009_auto_20210202_0319.py
  users/models.py
  users/utils.py
Labels: Status: 리뷰 요청

#9 [16기 장준영] Add: users socail_login & password_reset
  bestgo/settings.py
  users/tests.py
  users/urls.py
  users/utils.py
  users/views.py
Labels: Status: 리뷰 요청

#10 [16기 장준영] Add: profile_CRUD
  bestgo/settings.py
  users/templates/email.html
  users/tests.py
  users/urls.py
  users/utils.py
  users/views.py
Labels: Status: Accepted

#11 [16기정지원] Add : Request&Qoutation Views
  services/migrations/0007_requestmastermatch_priority.py
  services/migrations/0008_auto_20210203_1212.py
  services/migrations/0009_auto_20210203_1213.py
  services/migrations/0010_request_choices.py
  services/migrations/0011_auto_20210203_1349.py
  services/models.py
  services/urls.py
  services/utils.py
  services/views.py
  users/management/commands/seed_users.py
Labels: Status: 리뷰 요청

#12 [16기 정지원]Quotation과 Detail 뷰스 작성
  services/urls.py
  services/views.py
Labels: Status: 수정 요청
